---
- name: Restart
  shell: sleep 2 && /sbin/shutdown -r now 'Ansible Reboot triggered'
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for restart to finish
  wait_for_connection:
    delay: 50
