---
- hosts: rpis
  vars:
    u2dir: /home/pi/opt/u2init-release
    atxserver: "{{ lookup('env', 'ATXSERVER_URL') }}"
  tasks:
  - debug:
      msg: atx-server url is {{atxserver}}
  - name: copy start.sh.j2 to start.sh
    template:
      src: ./start.sh.j2
      dest: "{{u2dir}}/start.sh"
  - name: create u2init-release directory
    file: dest={{u2dir}} state=directory
  - name: copy pm2.json
    copy: src=pm2.json dest={{u2dir}}
  - name: copy index.html
    copy: src=../index.html dest={{u2dir}}
  - name: copy u2init
    copy: src=../u2init dest={{u2dir}} mode=755
  - name: mkdir resources directory
    file:
      dest: "{{u2dir}}/resources"
      state: directory
  - name: unarchive zip
    unarchive:
      src: ../resources/stf-binaries.zip
      dest: "{{u2dir}}/resources/"
  - command: pm2 stop u2init
    sudo: yes
    ignore_errors: True
  - command: pm2 start {{u2dir}}/pm2.json
    sudo: yes
  - command: pm2 save
    sudo: yes

